#!/usr/bin/env python3
"""Generate branch delay-slot variants for the C6000 SLEIGH module.

Writes data/languages/c6000_branch.sinc.

A C6000 branch takes effect after five delay cycles; the execute packets
issued in those cycles run on both the taken and the fall-through path.  By
default the module lifts a branch as an immediate jump, so on the taken path
the decompiler never sees that work.

For every root constructor that branches (B, BNOP, BDEC, BPOS, B IRP/NRP and
the compact forms) this generator emits a variant selected by the noflow
context bit ep_br=1.  The variant

  1. captures the condition (BR_c) and register target (BR_t) at issue, as the
     hardware does, since delay-slot code may change the predicate register;
  2. inlines the p-code of the delay-slot instructions with SLEIGH's
     delayslot directive (BrDs; ep_ds gives the window in halfwords);
  3. then branches on the captured values.

Ghidra then treats the window as delay slots: the branch's fall-through is
the first address after the window, and the decompiler sees the window's
p-code on both paths.  C6000ParallelSemanticsAnalyzer sets ep_br / ep_ds
only where the window holds real work and nothing in it breaks the model.
CALLP is not varied: its five delay cycles are its own NOPs.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LANG = ROOT / "data" / "languages"
OUT = LANG / "c6000_branch.sinc"
SOURCES = ["c6000.sinc", "c6000_decode.sinc", "c6000_manual.sinc", "c6000_compact.sinc"]
MAX_DS = 127  # ep_ds is seven bits of halfwords

T = r"(\w+)"
IND = r"(?:c6000_sem_b_ind\((\w+)\)|goto \[(\w+)\])"
RULES = [
    (rf"^\{{ goto {T}; \}}$",
     lambda m: f"build BrDs; goto {m[1]};"),
    (rf"^\{{ if \(Cond == 0\) goto <skip>; goto {T}; <skip> \}}$",
     lambda m: f"BR_c = Cond; build BrDs; if (BR_c == 0) goto <skip>; goto {m[1]}; <skip>"),
    (rf"^\{{ if \((.+?)\) goto {T}; \}}$",
     lambda m: f"BR_c = ({m[1]}); build BrDs; if (BR_c != 0) goto {m[2]};"),
    (rf"^\{{ {IND}; \}}$",
     lambda m: f"BR_t = {m[1] or m[2]}; build BrDs; goto [BR_t];"),
    (rf"^\{{ if \(Cond == 0\) goto <skip>; {IND}; <skip> \}}$",
     lambda m: f"BR_c = Cond; BR_t = {m[1] or m[2]}; build BrDs;"
               f" if (BR_c == 0) goto <skip>; goto [BR_t]; <skip>"),
    (r"^\{ if \(Cond == 0\) goto <skip>; if \(Dst s< 0\) goto <done>;"
     rf"( Dst = Dst - 1;)? goto {T}; <done> <skip> \}}$",
     lambda m: f"BR_c = 0; if (Cond == 0) goto <skip>; if (Dst s< 0) goto <skip>;"
               f"{m[1] or ''} BR_c = 1; <skip> build BrDs; if (BR_c != 0) goto {m[2]};"),
]


def constructors(text):
    lines = text.split("\n")
    i = 0
    while i < len(lines):
        if lines[i].startswith(":"):
            buf = [lines[i]]
            depth = lines[i].count("{") - lines[i].count("}")
            seen = "{" in lines[i]
            while not (seen and depth == 0):
                i += 1
                buf.append(lines[i])
                depth += lines[i].count("{") - lines[i].count("}")
                seen |= "{" in lines[i]
            yield re.sub(r"\s+", " ", " ".join(buf)).strip()
        i += 1


def is_branch(body):
    return re.search(r"goto (?!<|inst_next)|c6000_sem_b_ind", body) is not None


def variants(ctor):
    v = variant(ctor)
    if v is None:
        return []
    out = [v]
    # An unpredicated register branch not yet classified (c_branch_terminal=0)
    # shares the predicated constructor, whose skip keeps a fall-through for
    # code discovery. Lifted with its delay slots it becomes an indirect call
    # instead: unconditional, still falling through, and turned into a call
    # or return by the delayed-call or return analyzer's flow override.
    if "c_branch_terminal=0" in ctor and "Cond" in ctor:
        head, body = v.split("\n  ", 1)
        m = re.search(r"BR_t = (\w+);", body)
        out.append(f"{head.replace(' & ep_br=1', ' & creg=0 & z=0 & ep_br=1')}\n"
                   f"  {{ BR_t = {m[1]}; build BrDs; call [BR_t]; }}")
    return out


def variant(ctor):
    brace = ctor.index("{")
    head, body = ctor[:brace].rstrip(), ctor[brace:]
    body = re.sub(r"delayslot\(\d+\); ", "", body)
    if re.search(r"\bcall\b", body):
        return None  # CALLP: its delay cycles are its own NOPs
    for pattern, make in RULES:
        m = re.match(pattern, body)
        if m:
            break
    else:
        raise SystemExit(f"gen_branch: no rule for branch body {body!r} in {head!r}")
    # Constraint goes before an optional context-change block.
    block = re.search(r"\s\[[^\]]*\]$", head)
    if block:
        head = head[:block.start()] + " & ep_br=1 & BrDs" + head[block.start():]
    else:
        head += " & ep_br=1 & BrDs"
    return f"{head}\n  {{ {make(m)} }}"


def branch_sinc():
    w = ["# GENERATED by tools/gen_branch.py - do not edit by hand.",
         "#",
         "# Branch delay slots: see the generator's docstring and",
         "# docs/internals.md (\"Branch delay slots\").",
         "",
         "define register offset=0x4300 size=4 [ BR_t ];",
         "define register offset=0x4304 size=1 [ BR_c ];",
         "",
         "BrDs: is ep_ds=0 { }"]
    for k in range(1, MAX_DS + 1):
        w.append(f"BrDs: is ep_ds={k} {{ delayslot({2 * k}); }}")
    w.append("")
    count = 0
    for name in SOURCES:
        for ctor in constructors((LANG / name).read_text()):
            if not is_branch(ctor[ctor.index("{"):]):
                continue
            for v in variants(ctor):
                w.append(v)
                count += 1
    return "\n".join(w) + "\n", count


if __name__ == "__main__":
    text, count = branch_sinc()
    OUT.write_text(text)
    print("wrote", OUT, count, "branch variants")
