#!/usr/bin/env python3
"""Generate execute-packet / delay-slot semantics for the C6000 SLEIGH module.

Writes data/languages/c6000_packet.sinc and refreshes the generated block of
context fields in data/languages/c6000.sinc (between the BEGIN/END markers).

Model (see docs/internals.md, "Packet-accurate p-code"):

  * Every instruction is wrapped by a root constructor that runs, in order,
    EpSave (R_sv = R), the instruction, EpPost and EpCommit.
  * PACKET stash (eps<R>): the instruction's write to R is parked in R_pk and
    R is restored, so later members of the same execute packet still read
    the pre-packet value.  The packet's last member commits R = R_pk (epc<R>).
  * DELAY stash (epd<R>): a multi-cycle result (load, multiply, FP) is parked
    in R_dl and R restored; the last member of the packet in which the result
    lands commits R = R_dl (epe<R>).
  * ep_cpre moves the commit before the instruction, for a packet whose last
    member is a branch; such a member never parks writes itself.
  * ep_any is set on every slot carrying any of these bits; slots without it
    keep their original p-code (and so their original flow type).

C6000ParallelSemanticsAnalyzer sets these noflow context bits only where a
hazard exists, so ordinary instructions keep their plain p-code.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LANG = ROOT / "data" / "languages"
OUT = LANG / "c6000_packet.sinc"
CTX = LANG / "c6000.sinc"

REGS = [f"A{i}" for i in range(32)] + [f"B{i}" for i in range(32)]
BANKS = [("eps", 32), ("epd", 96), ("epc", 160), ("epe", 224)]
BEGIN = "  # BEGIN generated by tools/gen_packet.py"
END = "  # END generated by tools/gen_packet.py"


def context_fields():
    lines = [BEGIN,
             "  ep_phase = (15,15) noflow  # 0: packet wrapper, 1: instruction proper",
             "  ep_cpre  = (16,16) noflow  # commit before the instruction (branch last)",
             "  ep_any   = (17,17) noflow  # any packet-semantics bit set on this slot",
             "  ep_br    = (18,18) noflow  # branch lifted with its delay slots (gen_branch.py)",
             "  ep_ds    = (19,25) noflow  # that branch's delay-slot window, in halfwords"]
    for prefix, base in BANKS:
        row = []
        for i, reg in enumerate(REGS):
            bit = base + i
            row.append(f"{prefix}{reg}=({bit},{bit})")
            if len(row) == 8:
                lines.append("  " + " ".join(row) + " noflow")
                row = []
    lines.append(END)
    return lines


def packet_sinc():
    w = []
    w.append("# GENERATED by tools/gen_packet.py - do not edit by hand.")
    w.append("#")
    w.append("# Execute-packet and delay-slot semantics.  See the generator's")
    w.append("# docstring and docs/internals.md for the model.")
    w.append("")
    for suffix, off in (("sv", 0x4000), ("pk", 0x4100), ("dl", 0x4200)):
        w.append(f"define register offset=0x{off:04x} size=4")
        names = [f"{r}_{suffix}" for r in REGS]
        for k in range(0, 64, 8):
            head = "  [ " if k == 0 else "    "
            tail = " ];" if k == 56 else ""
            w.append(head + " ".join(names[k:k + 8]) + tail)
    w.append("")
    for r in REGS:
        s, d, c, e = (f"eps{r}", f"epd{r}", f"epc{r}", f"epe{r}")
        w.append(f"EpSv{r}: is {s}=0 & {d}=0 {{ }}")
        w.append(f"EpSv{r}: is {s}=1 & {d}=0 {{ {r}_sv = {r}; }}")
        w.append(f"EpSv{r}: is {s}=0 & {d}=1 {{ {r}_sv = {r}; }}")
        w.append(f"EpSv{r}: is {s}=1 & {d}=1 {{ {r}_sv = {r}; }}")
        w.append(f"EpPo{r}: is {s}=0 & {d}=0 {{ }}")
        w.append(f"EpPo{r}: is {s}=1 & {d}=0 {{ {r}_pk = {r}; {r} = {r}_sv; }}")
        w.append(f"EpPo{r}: is {s}=0 & {d}=1 {{ {r}_dl = {r}; {r} = {r}_sv; }}")
        w.append(f"EpPo{r}: is {s}=1 & {d}=1 {{ {r}_dl = {r}; {r} = {r}_sv; }}")
        w.append(f"EpCo{r}: is {c}=0 & {e}=0 {{ }}")
        w.append(f"EpCo{r}: is {c}=1 & {e}=0 {{ {r} = {r}_pk; }}")
        w.append(f"EpCo{r}: is {c}=0 & {e}=1 {{ {r} = {r}_dl; }}")
        w.append(f"EpCo{r}: is {c}=1 & {e}=1 {{ {r} = {r}_pk; }}")
    w.append("")
    for kind in ("Sv", "Po", "Co"):
        for bank in "AB":
            ops = " & ".join(f"Ep{kind}{bank}{i}" for i in range(32))
            builds = " ".join(f"build Ep{kind}{bank}{i};" for i in range(32))
            w.append(f"Ep{kind}{bank}: is {ops} {{ {builds} }}")
        w.append(f"Ep{kind}: is Ep{kind}A & Ep{kind}B {{ build Ep{kind}A; build Ep{kind}B; }}")
    w.append("")
    # Untouched slots must keep exactly their old p-code: Ghidra derives flow
    # types from the constructor templates, so a build after a branch would
    # turn every branch into a conditional one.
    w.append(":^instruction is ep_phase=0 & ep_any=0 & instruction [ ep_phase=1; ]")
    w.append("  { build instruction; }")
    w.append(":^instruction is ep_phase=0 & ep_any=1 & ep_cpre=0 & EpSv & EpPo & EpCo & instruction")
    w.append("  [ ep_phase=1; ]")
    w.append("  { build EpSv; build instruction; build EpPo; build EpCo; }")
    w.append("# A branch ending its packet commits first; it never parks writes itself.")
    w.append(":^instruction is ep_phase=0 & ep_any=1 & ep_cpre=1 & EpCo & instruction")
    w.append("  [ ep_phase=1; ]")
    w.append("  { build EpCo; build instruction; }")
    return "\n".join(w) + "\n"


def refresh_context():
    lines = CTX.read_text().split("\n")
    if BEGIN in lines:
        a, b = lines.index(BEGIN), lines.index(END)
        lines[a:b + 1] = context_fields()
    else:
        # Insert before the terminating ';' of `define context contextreg`.
        start = next(i for i, l in enumerate(lines) if l.startswith("define context contextreg"))
        end = next(i for i in range(start, len(lines)) if lines[i].strip() == ";")
        lines[end:end] = context_fields()
    CTX.write_text("\n".join(lines))


if __name__ == "__main__":
    OUT.write_text(packet_sinc())
    refresh_context()
    print("wrote", OUT)
